// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoFile/Configure.proto

package proto;

public final class ConfigureProto {
  private ConfigureProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConfigureOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 timePeriod = 1;
    /**
     * <code>required int64 timePeriod = 1;</code>
     *
     * <pre>
     * ʱ������
     * </pre>
     */
    boolean hasTimePeriod();
    /**
     * <code>required int64 timePeriod = 1;</code>
     *
     * <pre>
     * ʱ������
     * </pre>
     */
    long getTimePeriod();

    // required int32 blockNum = 2;
    /**
     * <code>required int32 blockNum = 2;</code>
     *
     * <pre>
     * �ڴ����
     * </pre>
     */
    boolean hasBlockNum();
    /**
     * <code>required int32 blockNum = 2;</code>
     *
     * <pre>
     * �ڴ����
     * </pre>
     */
    int getBlockNum();

    // required int32 blockSize = 3;
    /**
     * <code>required int32 blockSize = 3;</code>
     *
     * <pre>
     * �ڴ��Ĵ�С
     * </pre>
     */
    boolean hasBlockSize();
    /**
     * <code>required int32 blockSize = 3;</code>
     *
     * <pre>
     * �ڴ��Ĵ�С
     * </pre>
     */
    int getBlockSize();

    // required int32 allotNum = 4;
    /**
     * <code>required int32 allotNum = 4;</code>
     *
     * <pre>
     * ÿ����ҵ�����ҳ����
     * </pre>
     */
    boolean hasAllotNum();
    /**
     * <code>required int32 allotNum = 4;</code>
     *
     * <pre>
     * ÿ����ҵ�����ҳ����
     * </pre>
     */
    int getAllotNum();

    // required int32 timeSlice = 5;
    /**
     * <code>required int32 timeSlice = 5;</code>
     *
     * <pre>
     * ʱ��Ƭ�Ĵ�С
     * </pre>
     */
    boolean hasTimeSlice();
    /**
     * <code>required int32 timeSlice = 5;</code>
     *
     * <pre>
     * ʱ��Ƭ�Ĵ�С
     * </pre>
     */
    int getTimeSlice();
  }
  /**
   * Protobuf type {@code Configure}
   */
  public static final class Configure extends
      com.google.protobuf.GeneratedMessage
      implements ConfigureOrBuilder,ProtoClass {
    // Use Configure.newBuilder() to construct.
    private Configure(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Configure(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Configure defaultInstance;
    public static Configure getDefaultInstance() {
      return defaultInstance;
    }

    public Configure getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Configure(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timePeriod_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              blockNum_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              blockSize_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              allotNum_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timeSlice_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ConfigureProto.internal_static_Configure_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ConfigureProto.internal_static_Configure_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ConfigureProto.Configure.class, proto.ConfigureProto.Configure.Builder.class);
    }

    public static com.google.protobuf.Parser<Configure> PARSER =
        new com.google.protobuf.AbstractParser<Configure>() {
      public Configure parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Configure(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Configure> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 timePeriod = 1;
    public static final int TIMEPERIOD_FIELD_NUMBER = 1;
    private long timePeriod_;
    /**
     * <code>required int64 timePeriod = 1;</code>
     *
     * <pre>
     * ʱ������
     * </pre>
     */
    public boolean hasTimePeriod() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 timePeriod = 1;</code>
     *
     * <pre>
     * ʱ������
     * </pre>
     */
    public long getTimePeriod() {
      return timePeriod_;
    }

    // required int32 blockNum = 2;
    public static final int BLOCKNUM_FIELD_NUMBER = 2;
    private int blockNum_;
    /**
     * <code>required int32 blockNum = 2;</code>
     *
     * <pre>
     * �ڴ����
     * </pre>
     */
    public boolean hasBlockNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 blockNum = 2;</code>
     *
     * <pre>
     * �ڴ����
     * </pre>
     */
    public int getBlockNum() {
      return blockNum_;
    }

    // required int32 blockSize = 3;
    public static final int BLOCKSIZE_FIELD_NUMBER = 3;
    private int blockSize_;
    /**
     * <code>required int32 blockSize = 3;</code>
     *
     * <pre>
     * �ڴ��Ĵ�С
     * </pre>
     */
    public boolean hasBlockSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 blockSize = 3;</code>
     *
     * <pre>
     * �ڴ��Ĵ�С
     * </pre>
     */
    public int getBlockSize() {
      return blockSize_;
    }

    // required int32 allotNum = 4;
    public static final int ALLOTNUM_FIELD_NUMBER = 4;
    private int allotNum_;
    /**
     * <code>required int32 allotNum = 4;</code>
     *
     * <pre>
     * ÿ����ҵ�����ҳ����
     * </pre>
     */
    public boolean hasAllotNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 allotNum = 4;</code>
     *
     * <pre>
     * ÿ����ҵ�����ҳ����
     * </pre>
     */
    public int getAllotNum() {
      return allotNum_;
    }

    // required int32 timeSlice = 5;
    public static final int TIMESLICE_FIELD_NUMBER = 5;
    private int timeSlice_;
    /**
     * <code>required int32 timeSlice = 5;</code>
     *
     * <pre>
     * ʱ��Ƭ�Ĵ�С
     * </pre>
     */
    public boolean hasTimeSlice() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 timeSlice = 5;</code>
     *
     * <pre>
     * ʱ��Ƭ�Ĵ�С
     * </pre>
     */
    public int getTimeSlice() {
      return timeSlice_;
    }

    private void initFields() {
      timePeriod_ = 0L;
      blockNum_ = 0;
      blockSize_ = 0;
      allotNum_ = 0;
      timeSlice_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTimePeriod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBlockNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBlockSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAllotNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeSlice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timePeriod_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, blockNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, blockSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, allotNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, timeSlice_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timePeriod_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, blockNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, blockSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, allotNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, timeSlice_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.ConfigureProto.Configure parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ConfigureProto.Configure parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ConfigureProto.Configure parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ConfigureProto.Configure parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ConfigureProto.Configure parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.ConfigureProto.Configure parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.ConfigureProto.Configure parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.ConfigureProto.Configure parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.ConfigureProto.Configure parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.ConfigureProto.Configure parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.ConfigureProto.Configure prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Configure}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.ConfigureProto.ConfigureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ConfigureProto.internal_static_Configure_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ConfigureProto.internal_static_Configure_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ConfigureProto.Configure.class, proto.ConfigureProto.Configure.Builder.class);
      }

      // Construct using proto.ConfigureProto.Configure.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timePeriod_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        blockNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        blockSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        allotNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        timeSlice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ConfigureProto.internal_static_Configure_descriptor;
      }

      public proto.ConfigureProto.Configure getDefaultInstanceForType() {
        return proto.ConfigureProto.Configure.getDefaultInstance();
      }

      public proto.ConfigureProto.Configure build() {
        proto.ConfigureProto.Configure result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ConfigureProto.Configure buildPartial() {
        proto.ConfigureProto.Configure result = new proto.ConfigureProto.Configure(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timePeriod_ = timePeriod_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.blockNum_ = blockNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.blockSize_ = blockSize_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.allotNum_ = allotNum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timeSlice_ = timeSlice_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ConfigureProto.Configure) {
          return mergeFrom((proto.ConfigureProto.Configure)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ConfigureProto.Configure other) {
        if (other == proto.ConfigureProto.Configure.getDefaultInstance()) return this;
        if (other.hasTimePeriod()) {
          setTimePeriod(other.getTimePeriod());
        }
        if (other.hasBlockNum()) {
          setBlockNum(other.getBlockNum());
        }
        if (other.hasBlockSize()) {
          setBlockSize(other.getBlockSize());
        }
        if (other.hasAllotNum()) {
          setAllotNum(other.getAllotNum());
        }
        if (other.hasTimeSlice()) {
          setTimeSlice(other.getTimeSlice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimePeriod()) {
          
          return false;
        }
        if (!hasBlockNum()) {
          
          return false;
        }
        if (!hasBlockSize()) {
          
          return false;
        }
        if (!hasAllotNum()) {
          
          return false;
        }
        if (!hasTimeSlice()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ConfigureProto.Configure parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ConfigureProto.Configure) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 timePeriod = 1;
      private long timePeriod_ ;
      /**
       * <code>required int64 timePeriod = 1;</code>
       *
       * <pre>
       * ʱ������
       * </pre>
       */
      public boolean hasTimePeriod() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 timePeriod = 1;</code>
       *
       * <pre>
       * ʱ������
       * </pre>
       */
      public long getTimePeriod() {
        return timePeriod_;
      }
      /**
       * <code>required int64 timePeriod = 1;</code>
       *
       * <pre>
       * ʱ������
       * </pre>
       */
      public Builder setTimePeriod(long value) {
        bitField0_ |= 0x00000001;
        timePeriod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timePeriod = 1;</code>
       *
       * <pre>
       * ʱ������
       * </pre>
       */
      public Builder clearTimePeriod() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timePeriod_ = 0L;
        onChanged();
        return this;
      }

      // required int32 blockNum = 2;
      private int blockNum_ ;
      /**
       * <code>required int32 blockNum = 2;</code>
       *
       * <pre>
       * �ڴ����
       * </pre>
       */
      public boolean hasBlockNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 blockNum = 2;</code>
       *
       * <pre>
       * �ڴ����
       * </pre>
       */
      public int getBlockNum() {
        return blockNum_;
      }
      /**
       * <code>required int32 blockNum = 2;</code>
       *
       * <pre>
       * �ڴ����
       * </pre>
       */
      public Builder setBlockNum(int value) {
        bitField0_ |= 0x00000002;
        blockNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 blockNum = 2;</code>
       *
       * <pre>
       * �ڴ����
       * </pre>
       */
      public Builder clearBlockNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        blockNum_ = 0;
        onChanged();
        return this;
      }

      // required int32 blockSize = 3;
      private int blockSize_ ;
      /**
       * <code>required int32 blockSize = 3;</code>
       *
       * <pre>
       * �ڴ��Ĵ�С
       * </pre>
       */
      public boolean hasBlockSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 blockSize = 3;</code>
       *
       * <pre>
       * �ڴ��Ĵ�С
       * </pre>
       */
      public int getBlockSize() {
        return blockSize_;
      }
      /**
       * <code>required int32 blockSize = 3;</code>
       *
       * <pre>
       * �ڴ��Ĵ�С
       * </pre>
       */
      public Builder setBlockSize(int value) {
        bitField0_ |= 0x00000004;
        blockSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 blockSize = 3;</code>
       *
       * <pre>
       * �ڴ��Ĵ�С
       * </pre>
       */
      public Builder clearBlockSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        blockSize_ = 0;
        onChanged();
        return this;
      }

      // required int32 allotNum = 4;
      private int allotNum_ ;
      /**
       * <code>required int32 allotNum = 4;</code>
       *
       * <pre>
       * ÿ����ҵ�����ҳ����
       * </pre>
       */
      public boolean hasAllotNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 allotNum = 4;</code>
       *
       * <pre>
       * ÿ����ҵ�����ҳ����
       * </pre>
       */
      public int getAllotNum() {
        return allotNum_;
      }
      /**
       * <code>required int32 allotNum = 4;</code>
       *
       * <pre>
       * ÿ����ҵ�����ҳ����
       * </pre>
       */
      public Builder setAllotNum(int value) {
        bitField0_ |= 0x00000008;
        allotNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 allotNum = 4;</code>
       *
       * <pre>
       * ÿ����ҵ�����ҳ����
       * </pre>
       */
      public Builder clearAllotNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        allotNum_ = 0;
        onChanged();
        return this;
      }

      // required int32 timeSlice = 5;
      private int timeSlice_ ;
      /**
       * <code>required int32 timeSlice = 5;</code>
       *
       * <pre>
       * ʱ��Ƭ�Ĵ�С
       * </pre>
       */
      public boolean hasTimeSlice() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 timeSlice = 5;</code>
       *
       * <pre>
       * ʱ��Ƭ�Ĵ�С
       * </pre>
       */
      public int getTimeSlice() {
        return timeSlice_;
      }
      /**
       * <code>required int32 timeSlice = 5;</code>
       *
       * <pre>
       * ʱ��Ƭ�Ĵ�С
       * </pre>
       */
      public Builder setTimeSlice(int value) {
        bitField0_ |= 0x00000010;
        timeSlice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 timeSlice = 5;</code>
       *
       * <pre>
       * ʱ��Ƭ�Ĵ�С
       * </pre>
       */
      public Builder clearTimeSlice() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timeSlice_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Configure)
    }

    static {
      defaultInstance = new Configure(true);
      defaultInstance.initFields();
    }

	@Override
	public int getId() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getFileName() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getFileValue() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getRunningIndex() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public int getReplaceBlock() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getMemoryValue() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getJobId() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getState() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getWaitTime() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getPercentage() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getMessage() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public long getCurrentTime() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getResult() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getDeviceName() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getUsedjobId() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getWaitingJobId() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getUseTimeSlice() {
		// TODO Auto-generated method stub
		return null;
	}

    // @@protoc_insertion_point(class_scope:Configure)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Configure_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Configure_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031protoFile/Configure.proto\"i\n\tConfigure" +
      "\022\022\n\ntimePeriod\030\001 \002(\003\022\020\n\010blockNum\030\002 \002(\005\022\021" +
      "\n\tblockSize\030\003 \002(\005\022\020\n\010allotNum\030\004 \002(\005\022\021\n\tt" +
      "imeSlice\030\005 \002(\005B\027\n\005protoB\016ConfigureProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Configure_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Configure_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Configure_descriptor,
              new java.lang.String[] { "TimePeriod", "BlockNum", "BlockSize", "AllotNum", "TimeSlice", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
