// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoFile/DeviceMessage.proto

package proto;

public final class DeviceMessageProto {
  private DeviceMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DeviceMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string deviceName = 1;
    /**
     * <code>required string deviceName = 1;</code>
     */
    boolean hasDeviceName();
    /**
     * <code>required string deviceName = 1;</code>
     */
    java.lang.String getDeviceName();
    /**
     * <code>required string deviceName = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceNameBytes();

    // required string state = 2;
    /**
     * <code>required string state = 2;</code>
     */
    boolean hasState();
    /**
     * <code>required string state = 2;</code>
     */
    java.lang.String getState();
    /**
     * <code>required string state = 2;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();

    // required string usedjobId = 3;
    /**
     * <code>required string usedjobId = 3;</code>
     */
    boolean hasUsedjobId();
    /**
     * <code>required string usedjobId = 3;</code>
     */
    java.lang.String getUsedjobId();
    /**
     * <code>required string usedjobId = 3;</code>
     */
    com.google.protobuf.ByteString
        getUsedjobIdBytes();

    // required string waitingJobId = 4;
    /**
     * <code>required string waitingJobId = 4;</code>
     */
    boolean hasWaitingJobId();
    /**
     * <code>required string waitingJobId = 4;</code>
     */
    java.lang.String getWaitingJobId();
    /**
     * <code>required string waitingJobId = 4;</code>
     */
    com.google.protobuf.ByteString
        getWaitingJobIdBytes();

    // required string useTimeSlice = 5;
    /**
     * <code>required string useTimeSlice = 5;</code>
     */
    boolean hasUseTimeSlice();
    /**
     * <code>required string useTimeSlice = 5;</code>
     */
    java.lang.String getUseTimeSlice();
    /**
     * <code>required string useTimeSlice = 5;</code>
     */
    com.google.protobuf.ByteString
        getUseTimeSliceBytes();
  }
  /**
   * Protobuf type {@code DeviceMessage}
   */
  public static final class DeviceMessage extends
      com.google.protobuf.GeneratedMessage
      implements DeviceMessageOrBuilder,ProtoClass {
    // Use DeviceMessage.newBuilder() to construct.
    private DeviceMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeviceMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeviceMessage defaultInstance;
    public static DeviceMessage getDefaultInstance() {
      return defaultInstance;
    }

    public DeviceMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              state_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              usedjobId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              waitingJobId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              useTimeSlice_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.DeviceMessageProto.internal_static_DeviceMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.DeviceMessageProto.internal_static_DeviceMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.DeviceMessageProto.DeviceMessage.class, proto.DeviceMessageProto.DeviceMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<DeviceMessage> PARSER =
        new com.google.protobuf.AbstractParser<DeviceMessage>() {
      public DeviceMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string deviceName = 1;
    public static final int DEVICENAME_FIELD_NUMBER = 1;
    private java.lang.Object deviceName_;
    /**
     * <code>required string deviceName = 1;</code>
     */
    public boolean hasDeviceName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string deviceName = 1;</code>
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string state = 2;
    public static final int STATE_FIELD_NUMBER = 2;
    private java.lang.Object state_;
    /**
     * <code>required string state = 2;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string state = 2;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          state_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string state = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string usedjobId = 3;
    public static final int USEDJOBID_FIELD_NUMBER = 3;
    private java.lang.Object usedjobId_;
    /**
     * <code>required string usedjobId = 3;</code>
     */
    public boolean hasUsedjobId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string usedjobId = 3;</code>
     */
    public java.lang.String getUsedjobId() {
      java.lang.Object ref = usedjobId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          usedjobId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string usedjobId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUsedjobIdBytes() {
      java.lang.Object ref = usedjobId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usedjobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string waitingJobId = 4;
    public static final int WAITINGJOBID_FIELD_NUMBER = 4;
    private java.lang.Object waitingJobId_;
    /**
     * <code>required string waitingJobId = 4;</code>
     */
    public boolean hasWaitingJobId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string waitingJobId = 4;</code>
     */
    public java.lang.String getWaitingJobId() {
      java.lang.Object ref = waitingJobId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          waitingJobId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string waitingJobId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getWaitingJobIdBytes() {
      java.lang.Object ref = waitingJobId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        waitingJobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string useTimeSlice = 5;
    public static final int USETIMESLICE_FIELD_NUMBER = 5;
    private java.lang.Object useTimeSlice_;
    /**
     * <code>required string useTimeSlice = 5;</code>
     */
    public boolean hasUseTimeSlice() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string useTimeSlice = 5;</code>
     */
    public java.lang.String getUseTimeSlice() {
      java.lang.Object ref = useTimeSlice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          useTimeSlice_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string useTimeSlice = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUseTimeSliceBytes() {
      java.lang.Object ref = useTimeSlice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        useTimeSlice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      deviceName_ = "";
      state_ = "";
      usedjobId_ = "";
      waitingJobId_ = "";
      useTimeSlice_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDeviceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUsedjobId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWaitingJobId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUseTimeSlice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getStateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUsedjobIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getWaitingJobIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUseTimeSliceBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getStateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUsedjobIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getWaitingJobIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUseTimeSliceBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.DeviceMessageProto.DeviceMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.DeviceMessageProto.DeviceMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.DeviceMessageProto.DeviceMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.DeviceMessageProto.DeviceMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.DeviceMessageProto.DeviceMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.DeviceMessageProto.DeviceMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.DeviceMessageProto.DeviceMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.DeviceMessageProto.DeviceMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.DeviceMessageProto.DeviceMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.DeviceMessageProto.DeviceMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.DeviceMessageProto.DeviceMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeviceMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.DeviceMessageProto.DeviceMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.DeviceMessageProto.internal_static_DeviceMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.DeviceMessageProto.internal_static_DeviceMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.DeviceMessageProto.DeviceMessage.class, proto.DeviceMessageProto.DeviceMessage.Builder.class);
      }

      // Construct using proto.DeviceMessageProto.DeviceMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        usedjobId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        waitingJobId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        useTimeSlice_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.DeviceMessageProto.internal_static_DeviceMessage_descriptor;
      }

      public proto.DeviceMessageProto.DeviceMessage getDefaultInstanceForType() {
        return proto.DeviceMessageProto.DeviceMessage.getDefaultInstance();
      }

      public proto.DeviceMessageProto.DeviceMessage build() {
        proto.DeviceMessageProto.DeviceMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.DeviceMessageProto.DeviceMessage buildPartial() {
        proto.DeviceMessageProto.DeviceMessage result = new proto.DeviceMessageProto.DeviceMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceName_ = deviceName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.usedjobId_ = usedjobId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.waitingJobId_ = waitingJobId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.useTimeSlice_ = useTimeSlice_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.DeviceMessageProto.DeviceMessage) {
          return mergeFrom((proto.DeviceMessageProto.DeviceMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.DeviceMessageProto.DeviceMessage other) {
        if (other == proto.DeviceMessageProto.DeviceMessage.getDefaultInstance()) return this;
        if (other.hasDeviceName()) {
          bitField0_ |= 0x00000001;
          deviceName_ = other.deviceName_;
          onChanged();
        }
        if (other.hasState()) {
          bitField0_ |= 0x00000002;
          state_ = other.state_;
          onChanged();
        }
        if (other.hasUsedjobId()) {
          bitField0_ |= 0x00000004;
          usedjobId_ = other.usedjobId_;
          onChanged();
        }
        if (other.hasWaitingJobId()) {
          bitField0_ |= 0x00000008;
          waitingJobId_ = other.waitingJobId_;
          onChanged();
        }
        if (other.hasUseTimeSlice()) {
          bitField0_ |= 0x00000010;
          useTimeSlice_ = other.useTimeSlice_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeviceName()) {
          
          return false;
        }
        if (!hasState()) {
          
          return false;
        }
        if (!hasUsedjobId()) {
          
          return false;
        }
        if (!hasWaitingJobId()) {
          
          return false;
        }
        if (!hasUseTimeSlice()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.DeviceMessageProto.DeviceMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.DeviceMessageProto.DeviceMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string deviceName = 1;
      private java.lang.Object deviceName_ = "";
      /**
       * <code>required string deviceName = 1;</code>
       */
      public boolean hasDeviceName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string deviceName = 1;</code>
       */
      public java.lang.String getDeviceName() {
        java.lang.Object ref = deviceName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string deviceName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        java.lang.Object ref = deviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceName = 1;</code>
       */
      public Builder setDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceName = 1;</code>
       */
      public Builder clearDeviceName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceName = 1;</code>
       */
      public Builder setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceName_ = value;
        onChanged();
        return this;
      }

      // required string state = 2;
      private java.lang.Object state_ = "";
      /**
       * <code>required string state = 2;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string state = 2;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string state = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string state = 2;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string state = 2;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>required string state = 2;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        state_ = value;
        onChanged();
        return this;
      }

      // required string usedjobId = 3;
      private java.lang.Object usedjobId_ = "";
      /**
       * <code>required string usedjobId = 3;</code>
       */
      public boolean hasUsedjobId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string usedjobId = 3;</code>
       */
      public java.lang.String getUsedjobId() {
        java.lang.Object ref = usedjobId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          usedjobId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string usedjobId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUsedjobIdBytes() {
        java.lang.Object ref = usedjobId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usedjobId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string usedjobId = 3;</code>
       */
      public Builder setUsedjobId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        usedjobId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string usedjobId = 3;</code>
       */
      public Builder clearUsedjobId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        usedjobId_ = getDefaultInstance().getUsedjobId();
        onChanged();
        return this;
      }
      /**
       * <code>required string usedjobId = 3;</code>
       */
      public Builder setUsedjobIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        usedjobId_ = value;
        onChanged();
        return this;
      }

      // required string waitingJobId = 4;
      private java.lang.Object waitingJobId_ = "";
      /**
       * <code>required string waitingJobId = 4;</code>
       */
      public boolean hasWaitingJobId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string waitingJobId = 4;</code>
       */
      public java.lang.String getWaitingJobId() {
        java.lang.Object ref = waitingJobId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          waitingJobId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string waitingJobId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getWaitingJobIdBytes() {
        java.lang.Object ref = waitingJobId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          waitingJobId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string waitingJobId = 4;</code>
       */
      public Builder setWaitingJobId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        waitingJobId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string waitingJobId = 4;</code>
       */
      public Builder clearWaitingJobId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        waitingJobId_ = getDefaultInstance().getWaitingJobId();
        onChanged();
        return this;
      }
      /**
       * <code>required string waitingJobId = 4;</code>
       */
      public Builder setWaitingJobIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        waitingJobId_ = value;
        onChanged();
        return this;
      }

      // required string useTimeSlice = 5;
      private java.lang.Object useTimeSlice_ = "";
      /**
       * <code>required string useTimeSlice = 5;</code>
       */
      public boolean hasUseTimeSlice() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string useTimeSlice = 5;</code>
       */
      public java.lang.String getUseTimeSlice() {
        java.lang.Object ref = useTimeSlice_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          useTimeSlice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string useTimeSlice = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUseTimeSliceBytes() {
        java.lang.Object ref = useTimeSlice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          useTimeSlice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string useTimeSlice = 5;</code>
       */
      public Builder setUseTimeSlice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        useTimeSlice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string useTimeSlice = 5;</code>
       */
      public Builder clearUseTimeSlice() {
        bitField0_ = (bitField0_ & ~0x00000010);
        useTimeSlice_ = getDefaultInstance().getUseTimeSlice();
        onChanged();
        return this;
      }
      /**
       * <code>required string useTimeSlice = 5;</code>
       */
      public Builder setUseTimeSliceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        useTimeSlice_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DeviceMessage)
    }

    static {
      defaultInstance = new DeviceMessage(true);
      defaultInstance.initFields();
    }

	@Override
	public long getTimePeriod() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getBlockNum() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getBlockSize() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getAllotNum() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getTimeSlice() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getId() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getFileName() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getFileValue() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getRunningIndex() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public int getReplaceBlock() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getMemoryValue() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getJobId() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getWaitTime() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getPercentage() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getMessage() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public long getCurrentTime() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getResult() {
		// TODO Auto-generated method stub
		return null;
	}

    // @@protoc_insertion_point(class_scope:DeviceMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DeviceMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DeviceMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035protoFile/DeviceMessage.proto\"q\n\rDevic" +
      "eMessage\022\022\n\ndeviceName\030\001 \002(\t\022\r\n\005state\030\002 " +
      "\002(\t\022\021\n\tusedjobId\030\003 \002(\t\022\024\n\014waitingJobId\030\004" +
      " \002(\t\022\024\n\014useTimeSlice\030\005 \002(\tB\033\n\005protoB\022Dev" +
      "iceMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DeviceMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DeviceMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DeviceMessage_descriptor,
              new java.lang.String[] { "DeviceName", "State", "UsedjobId", "WaitingJobId", "UseTimeSlice", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
