// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoFile/MemoryMessage.proto

package proto;

public final class MemoryMessageProto {
  private MemoryMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MemoryMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string runningIndex = 1;
    /**
     * <code>required string runningIndex = 1;</code>
     */
    boolean hasRunningIndex();
    /**
     * <code>required string runningIndex = 1;</code>
     */
    java.lang.String getRunningIndex();
    /**
     * <code>required string runningIndex = 1;</code>
     */
    com.google.protobuf.ByteString
        getRunningIndexBytes();

    // required int32 replaceBlock = 2;
    /**
     * <code>required int32 replaceBlock = 2;</code>
     */
    boolean hasReplaceBlock();
    /**
     * <code>required int32 replaceBlock = 2;</code>
     */
    int getReplaceBlock();

    // required string memoryValue = 3;
    /**
     * <code>required string memoryValue = 3;</code>
     */
    boolean hasMemoryValue();
    /**
     * <code>required string memoryValue = 3;</code>
     */
    java.lang.String getMemoryValue();
    /**
     * <code>required string memoryValue = 3;</code>
     */
    com.google.protobuf.ByteString
        getMemoryValueBytes();
  }
  /**
   * Protobuf type {@code MemoryMessage}
   */
  public static final class MemoryMessage extends
      com.google.protobuf.GeneratedMessage
      implements MemoryMessageOrBuilder,ProtoClass {
    // Use MemoryMessage.newBuilder() to construct.
    private MemoryMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MemoryMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MemoryMessage defaultInstance;
    public static MemoryMessage getDefaultInstance() {
      return defaultInstance;
    }

    public MemoryMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MemoryMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              runningIndex_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              replaceBlock_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              memoryValue_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.MemoryMessageProto.internal_static_MemoryMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.MemoryMessageProto.internal_static_MemoryMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.MemoryMessageProto.MemoryMessage.class, proto.MemoryMessageProto.MemoryMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<MemoryMessage> PARSER =
        new com.google.protobuf.AbstractParser<MemoryMessage>() {
      public MemoryMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MemoryMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MemoryMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string runningIndex = 1;
    public static final int RUNNINGINDEX_FIELD_NUMBER = 1;
    private java.lang.Object runningIndex_;
    /**
     * <code>required string runningIndex = 1;</code>
     */
    public boolean hasRunningIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string runningIndex = 1;</code>
     */
    public java.lang.String getRunningIndex() {
      java.lang.Object ref = runningIndex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          runningIndex_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string runningIndex = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRunningIndexBytes() {
      java.lang.Object ref = runningIndex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        runningIndex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 replaceBlock = 2;
    public static final int REPLACEBLOCK_FIELD_NUMBER = 2;
    private int replaceBlock_;
    /**
     * <code>required int32 replaceBlock = 2;</code>
     */
    public boolean hasReplaceBlock() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 replaceBlock = 2;</code>
     */
    public int getReplaceBlock() {
      return replaceBlock_;
    }

    // required string memoryValue = 3;
    public static final int MEMORYVALUE_FIELD_NUMBER = 3;
    private java.lang.Object memoryValue_;
    /**
     * <code>required string memoryValue = 3;</code>
     */
    public boolean hasMemoryValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string memoryValue = 3;</code>
     */
    public java.lang.String getMemoryValue() {
      java.lang.Object ref = memoryValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          memoryValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string memoryValue = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMemoryValueBytes() {
      java.lang.Object ref = memoryValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memoryValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      runningIndex_ = "";
      replaceBlock_ = 0;
      memoryValue_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRunningIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReplaceBlock()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMemoryValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRunningIndexBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, replaceBlock_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMemoryValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRunningIndexBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, replaceBlock_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMemoryValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.MemoryMessageProto.MemoryMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MemoryMessageProto.MemoryMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MemoryMessageProto.MemoryMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MemoryMessageProto.MemoryMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MemoryMessageProto.MemoryMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.MemoryMessageProto.MemoryMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.MemoryMessageProto.MemoryMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.MemoryMessageProto.MemoryMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.MemoryMessageProto.MemoryMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.MemoryMessageProto.MemoryMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.MemoryMessageProto.MemoryMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MemoryMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.MemoryMessageProto.MemoryMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.MemoryMessageProto.internal_static_MemoryMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.MemoryMessageProto.internal_static_MemoryMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.MemoryMessageProto.MemoryMessage.class, proto.MemoryMessageProto.MemoryMessage.Builder.class);
      }

      // Construct using proto.MemoryMessageProto.MemoryMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        runningIndex_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        replaceBlock_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        memoryValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.MemoryMessageProto.internal_static_MemoryMessage_descriptor;
      }

      public proto.MemoryMessageProto.MemoryMessage getDefaultInstanceForType() {
        return proto.MemoryMessageProto.MemoryMessage.getDefaultInstance();
      }

      public proto.MemoryMessageProto.MemoryMessage build() {
        proto.MemoryMessageProto.MemoryMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.MemoryMessageProto.MemoryMessage buildPartial() {
        proto.MemoryMessageProto.MemoryMessage result = new proto.MemoryMessageProto.MemoryMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.runningIndex_ = runningIndex_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.replaceBlock_ = replaceBlock_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.memoryValue_ = memoryValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.MemoryMessageProto.MemoryMessage) {
          return mergeFrom((proto.MemoryMessageProto.MemoryMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.MemoryMessageProto.MemoryMessage other) {
        if (other == proto.MemoryMessageProto.MemoryMessage.getDefaultInstance()) return this;
        if (other.hasRunningIndex()) {
          bitField0_ |= 0x00000001;
          runningIndex_ = other.runningIndex_;
          onChanged();
        }
        if (other.hasReplaceBlock()) {
          setReplaceBlock(other.getReplaceBlock());
        }
        if (other.hasMemoryValue()) {
          bitField0_ |= 0x00000004;
          memoryValue_ = other.memoryValue_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRunningIndex()) {
          
          return false;
        }
        if (!hasReplaceBlock()) {
          
          return false;
        }
        if (!hasMemoryValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.MemoryMessageProto.MemoryMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.MemoryMessageProto.MemoryMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string runningIndex = 1;
      private java.lang.Object runningIndex_ = "";
      /**
       * <code>required string runningIndex = 1;</code>
       */
      public boolean hasRunningIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string runningIndex = 1;</code>
       */
      public java.lang.String getRunningIndex() {
        java.lang.Object ref = runningIndex_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          runningIndex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string runningIndex = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRunningIndexBytes() {
        java.lang.Object ref = runningIndex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          runningIndex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string runningIndex = 1;</code>
       */
      public Builder setRunningIndex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        runningIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string runningIndex = 1;</code>
       */
      public Builder clearRunningIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        runningIndex_ = getDefaultInstance().getRunningIndex();
        onChanged();
        return this;
      }
      /**
       * <code>required string runningIndex = 1;</code>
       */
      public Builder setRunningIndexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        runningIndex_ = value;
        onChanged();
        return this;
      }

      // required int32 replaceBlock = 2;
      private int replaceBlock_ ;
      /**
       * <code>required int32 replaceBlock = 2;</code>
       */
      public boolean hasReplaceBlock() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 replaceBlock = 2;</code>
       */
      public int getReplaceBlock() {
        return replaceBlock_;
      }
      /**
       * <code>required int32 replaceBlock = 2;</code>
       */
      public Builder setReplaceBlock(int value) {
        bitField0_ |= 0x00000002;
        replaceBlock_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 replaceBlock = 2;</code>
       */
      public Builder clearReplaceBlock() {
        bitField0_ = (bitField0_ & ~0x00000002);
        replaceBlock_ = 0;
        onChanged();
        return this;
      }

      // required string memoryValue = 3;
      private java.lang.Object memoryValue_ = "";
      /**
       * <code>required string memoryValue = 3;</code>
       */
      public boolean hasMemoryValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string memoryValue = 3;</code>
       */
      public java.lang.String getMemoryValue() {
        java.lang.Object ref = memoryValue_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          memoryValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string memoryValue = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMemoryValueBytes() {
        java.lang.Object ref = memoryValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memoryValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string memoryValue = 3;</code>
       */
      public Builder setMemoryValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        memoryValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string memoryValue = 3;</code>
       */
      public Builder clearMemoryValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        memoryValue_ = getDefaultInstance().getMemoryValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string memoryValue = 3;</code>
       */
      public Builder setMemoryValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        memoryValue_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MemoryMessage)
    }

    static {
      defaultInstance = new MemoryMessage(true);
      defaultInstance.initFields();
    }

	@Override
	public long getTimePeriod() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getBlockNum() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getBlockSize() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getAllotNum() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getTimeSlice() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getId() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getFileName() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getFileValue() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getJobId() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getState() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getWaitTime() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getPercentage() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getMessage() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public long getCurrentTime() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getResult() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getDeviceName() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getUsedjobId() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getWaitingJobId() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getUseTimeSlice() {
		// TODO Auto-generated method stub
		return null;
	}

    // @@protoc_insertion_point(class_scope:MemoryMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MemoryMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MemoryMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035protoFile/MemoryMessage.proto\"P\n\rMemor" +
      "yMessage\022\024\n\014runningIndex\030\001 \002(\t\022\024\n\014replac" +
      "eBlock\030\002 \002(\005\022\023\n\013memoryValue\030\003 \002(\tB\033\n\005pro" +
      "toB\022MemoryMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MemoryMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MemoryMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MemoryMessage_descriptor,
              new java.lang.String[] { "RunningIndex", "ReplaceBlock", "MemoryValue", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
