// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoFile/ProcessMessage.proto

package proto;

public final class ProcessMessageProto {
  private ProcessMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProcessMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string jobId = 1;
    /**
     * <code>required string jobId = 1;</code>
     */
    boolean hasJobId();
    /**
     * <code>required string jobId = 1;</code>
     */
    java.lang.String getJobId();
    /**
     * <code>required string jobId = 1;</code>
     */
    com.google.protobuf.ByteString
        getJobIdBytes();

    // required string state = 2;
    /**
     * <code>required string state = 2;</code>
     */
    boolean hasState();
    /**
     * <code>required string state = 2;</code>
     */
    java.lang.String getState();
    /**
     * <code>required string state = 2;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();

    // required string waitTime = 3;
    /**
     * <code>required string waitTime = 3;</code>
     */
    boolean hasWaitTime();
    /**
     * <code>required string waitTime = 3;</code>
     */
    java.lang.String getWaitTime();
    /**
     * <code>required string waitTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getWaitTimeBytes();

    // required string percentage = 4;
    /**
     * <code>required string percentage = 4;</code>
     */
    boolean hasPercentage();
    /**
     * <code>required string percentage = 4;</code>
     */
    java.lang.String getPercentage();
    /**
     * <code>required string percentage = 4;</code>
     */
    com.google.protobuf.ByteString
        getPercentageBytes();
  }
  /**
   * Protobuf type {@code ProcessMessage}
   */
  public static final class ProcessMessage extends
      com.google.protobuf.GeneratedMessage
      implements ProcessMessageOrBuilder,ProtoClass {
    // Use ProcessMessage.newBuilder() to construct.
    private ProcessMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProcessMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProcessMessage defaultInstance;
    public static ProcessMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ProcessMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProcessMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              jobId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              state_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              waitTime_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              percentage_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ProcessMessageProto.internal_static_ProcessMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ProcessMessageProto.internal_static_ProcessMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ProcessMessageProto.ProcessMessage.class, proto.ProcessMessageProto.ProcessMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ProcessMessage> PARSER =
        new com.google.protobuf.AbstractParser<ProcessMessage>() {
      public ProcessMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProcessMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProcessMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string jobId = 1;
    public static final int JOBID_FIELD_NUMBER = 1;
    private java.lang.Object jobId_;
    /**
     * <code>required string jobId = 1;</code>
     */
    public boolean hasJobId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string jobId = 1;</code>
     */
    public java.lang.String getJobId() {
      java.lang.Object ref = jobId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jobId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string jobId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJobIdBytes() {
      java.lang.Object ref = jobId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string state = 2;
    public static final int STATE_FIELD_NUMBER = 2;
    private java.lang.Object state_;
    /**
     * <code>required string state = 2;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string state = 2;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          state_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string state = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string waitTime = 3;
    public static final int WAITTIME_FIELD_NUMBER = 3;
    private java.lang.Object waitTime_;
    /**
     * <code>required string waitTime = 3;</code>
     */
    public boolean hasWaitTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string waitTime = 3;</code>
     */
    public java.lang.String getWaitTime() {
      java.lang.Object ref = waitTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          waitTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string waitTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getWaitTimeBytes() {
      java.lang.Object ref = waitTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        waitTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string percentage = 4;
    public static final int PERCENTAGE_FIELD_NUMBER = 4;
    private java.lang.Object percentage_;
    /**
     * <code>required string percentage = 4;</code>
     */
    public boolean hasPercentage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string percentage = 4;</code>
     */
    public java.lang.String getPercentage() {
      java.lang.Object ref = percentage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          percentage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string percentage = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPercentageBytes() {
      java.lang.Object ref = percentage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        percentage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      jobId_ = "";
      state_ = "";
      waitTime_ = "";
      percentage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasJobId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWaitTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPercentage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getJobIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getStateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getWaitTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPercentageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getJobIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getStateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getWaitTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPercentageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.ProcessMessageProto.ProcessMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProcessMessageProto.ProcessMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProcessMessageProto.ProcessMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProcessMessageProto.ProcessMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProcessMessageProto.ProcessMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.ProcessMessageProto.ProcessMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.ProcessMessageProto.ProcessMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.ProcessMessageProto.ProcessMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.ProcessMessageProto.ProcessMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.ProcessMessageProto.ProcessMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.ProcessMessageProto.ProcessMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProcessMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.ProcessMessageProto.ProcessMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ProcessMessageProto.internal_static_ProcessMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ProcessMessageProto.internal_static_ProcessMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ProcessMessageProto.ProcessMessage.class, proto.ProcessMessageProto.ProcessMessage.Builder.class);
      }

      // Construct using proto.ProcessMessageProto.ProcessMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        jobId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        waitTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        percentage_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ProcessMessageProto.internal_static_ProcessMessage_descriptor;
      }

      public proto.ProcessMessageProto.ProcessMessage getDefaultInstanceForType() {
        return proto.ProcessMessageProto.ProcessMessage.getDefaultInstance();
      }

      public proto.ProcessMessageProto.ProcessMessage build() {
        proto.ProcessMessageProto.ProcessMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ProcessMessageProto.ProcessMessage buildPartial() {
        proto.ProcessMessageProto.ProcessMessage result = new proto.ProcessMessageProto.ProcessMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jobId_ = jobId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.waitTime_ = waitTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.percentage_ = percentage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ProcessMessageProto.ProcessMessage) {
          return mergeFrom((proto.ProcessMessageProto.ProcessMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ProcessMessageProto.ProcessMessage other) {
        if (other == proto.ProcessMessageProto.ProcessMessage.getDefaultInstance()) return this;
        if (other.hasJobId()) {
          bitField0_ |= 0x00000001;
          jobId_ = other.jobId_;
          onChanged();
        }
        if (other.hasState()) {
          bitField0_ |= 0x00000002;
          state_ = other.state_;
          onChanged();
        }
        if (other.hasWaitTime()) {
          bitField0_ |= 0x00000004;
          waitTime_ = other.waitTime_;
          onChanged();
        }
        if (other.hasPercentage()) {
          bitField0_ |= 0x00000008;
          percentage_ = other.percentage_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasJobId()) {
          
          return false;
        }
        if (!hasState()) {
          
          return false;
        }
        if (!hasWaitTime()) {
          
          return false;
        }
        if (!hasPercentage()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ProcessMessageProto.ProcessMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ProcessMessageProto.ProcessMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string jobId = 1;
      private java.lang.Object jobId_ = "";
      /**
       * <code>required string jobId = 1;</code>
       */
      public boolean hasJobId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string jobId = 1;</code>
       */
      public java.lang.String getJobId() {
        java.lang.Object ref = jobId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          jobId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string jobId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJobIdBytes() {
        java.lang.Object ref = jobId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jobId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string jobId = 1;</code>
       */
      public Builder setJobId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jobId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string jobId = 1;</code>
       */
      public Builder clearJobId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jobId_ = getDefaultInstance().getJobId();
        onChanged();
        return this;
      }
      /**
       * <code>required string jobId = 1;</code>
       */
      public Builder setJobIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jobId_ = value;
        onChanged();
        return this;
      }

      // required string state = 2;
      private java.lang.Object state_ = "";
      /**
       * <code>required string state = 2;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string state = 2;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string state = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string state = 2;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string state = 2;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>required string state = 2;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        state_ = value;
        onChanged();
        return this;
      }

      // required string waitTime = 3;
      private java.lang.Object waitTime_ = "";
      /**
       * <code>required string waitTime = 3;</code>
       */
      public boolean hasWaitTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string waitTime = 3;</code>
       */
      public java.lang.String getWaitTime() {
        java.lang.Object ref = waitTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          waitTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string waitTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getWaitTimeBytes() {
        java.lang.Object ref = waitTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          waitTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string waitTime = 3;</code>
       */
      public Builder setWaitTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        waitTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string waitTime = 3;</code>
       */
      public Builder clearWaitTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        waitTime_ = getDefaultInstance().getWaitTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string waitTime = 3;</code>
       */
      public Builder setWaitTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        waitTime_ = value;
        onChanged();
        return this;
      }

      // required string percentage = 4;
      private java.lang.Object percentage_ = "";
      /**
       * <code>required string percentage = 4;</code>
       */
      public boolean hasPercentage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string percentage = 4;</code>
       */
      public java.lang.String getPercentage() {
        java.lang.Object ref = percentage_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          percentage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string percentage = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPercentageBytes() {
        java.lang.Object ref = percentage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          percentage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string percentage = 4;</code>
       */
      public Builder setPercentage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        percentage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string percentage = 4;</code>
       */
      public Builder clearPercentage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        percentage_ = getDefaultInstance().getPercentage();
        onChanged();
        return this;
      }
      /**
       * <code>required string percentage = 4;</code>
       */
      public Builder setPercentageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        percentage_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProcessMessage)
    }

    static {
      defaultInstance = new ProcessMessage(true);
      defaultInstance.initFields();
    }

	@Override
	public long getTimePeriod() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getBlockNum() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getBlockSize() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getAllotNum() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getTimeSlice() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getId() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getFileName() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getFileValue() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getRunningIndex() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public int getReplaceBlock() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getMemoryValue() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getMessage() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public long getCurrentTime() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getResult() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getDeviceName() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getUsedjobId() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getWaitingJobId() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getUseTimeSlice() {
		// TODO Auto-generated method stub
		return null;
	}

    // @@protoc_insertion_point(class_scope:ProcessMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProcessMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProcessMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036protoFile/ProcessMessage.proto\"T\n\016Proc" +
      "essMessage\022\r\n\005jobId\030\001 \002(\t\022\r\n\005state\030\002 \002(\t" +
      "\022\020\n\010waitTime\030\003 \002(\t\022\022\n\npercentage\030\004 \002(\tB\034" +
      "\n\005protoB\023ProcessMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProcessMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProcessMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProcessMessage_descriptor,
              new java.lang.String[] { "JobId", "State", "WaitTime", "Percentage", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
