// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoFile/Timer.proto

package proto;

public final class TimerProto {
  private TimerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TimerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 currentTime = 1;
    /**
     * <code>required int64 currentTime = 1;</code>
     */
    boolean hasCurrentTime();
    /**
     * <code>required int64 currentTime = 1;</code>
     */
    long getCurrentTime();
  }
  /**
   * Protobuf type {@code Timer}
   */
  public static final class Timer extends
      com.google.protobuf.GeneratedMessage
      implements TimerOrBuilder,ProtoClass {
    // Use Timer.newBuilder() to construct.
    private Timer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Timer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Timer defaultInstance;
    public static Timer getDefaultInstance() {
      return defaultInstance;
    }

    public Timer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Timer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              currentTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.TimerProto.internal_static_Timer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.TimerProto.internal_static_Timer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.TimerProto.Timer.class, proto.TimerProto.Timer.Builder.class);
    }

    public static com.google.protobuf.Parser<Timer> PARSER =
        new com.google.protobuf.AbstractParser<Timer>() {
      public Timer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Timer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Timer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 currentTime = 1;
    public static final int CURRENTTIME_FIELD_NUMBER = 1;
    private long currentTime_;
    /**
     * <code>required int64 currentTime = 1;</code>
     */
    public boolean hasCurrentTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 currentTime = 1;</code>
     */
    public long getCurrentTime() {
      return currentTime_;
    }

    private void initFields() {
      currentTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCurrentTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, currentTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, currentTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.TimerProto.Timer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.TimerProto.Timer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.TimerProto.Timer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.TimerProto.Timer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.TimerProto.Timer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.TimerProto.Timer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.TimerProto.Timer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.TimerProto.Timer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.TimerProto.Timer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.TimerProto.Timer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.TimerProto.Timer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Timer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.TimerProto.TimerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.TimerProto.internal_static_Timer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.TimerProto.internal_static_Timer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.TimerProto.Timer.class, proto.TimerProto.Timer.Builder.class);
      }

      // Construct using proto.TimerProto.Timer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        currentTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.TimerProto.internal_static_Timer_descriptor;
      }

      public proto.TimerProto.Timer getDefaultInstanceForType() {
        return proto.TimerProto.Timer.getDefaultInstance();
      }

      public proto.TimerProto.Timer build() {
        proto.TimerProto.Timer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.TimerProto.Timer buildPartial() {
        proto.TimerProto.Timer result = new proto.TimerProto.Timer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.currentTime_ = currentTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.TimerProto.Timer) {
          return mergeFrom((proto.TimerProto.Timer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.TimerProto.Timer other) {
        if (other == proto.TimerProto.Timer.getDefaultInstance()) return this;
        if (other.hasCurrentTime()) {
          setCurrentTime(other.getCurrentTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCurrentTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.TimerProto.Timer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.TimerProto.Timer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 currentTime = 1;
      private long currentTime_ ;
      /**
       * <code>required int64 currentTime = 1;</code>
       */
      public boolean hasCurrentTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 currentTime = 1;</code>
       */
      public long getCurrentTime() {
        return currentTime_;
      }
      /**
       * <code>required int64 currentTime = 1;</code>
       */
      public Builder setCurrentTime(long value) {
        bitField0_ |= 0x00000001;
        currentTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 currentTime = 1;</code>
       */
      public Builder clearCurrentTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currentTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Timer)
    }

    static {
      defaultInstance = new Timer(true);
      defaultInstance.initFields();
    }

	@Override
	public long getTimePeriod() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getBlockNum() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getBlockSize() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getAllotNum() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getTimeSlice() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public int getId() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getFileName() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getFileValue() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getRunningIndex() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public int getReplaceBlock() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String getMemoryValue() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getJobId() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getState() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getWaitTime() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getPercentage() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getMessage() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getResult() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getDeviceName() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getUsedjobId() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getWaitingJobId() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getUseTimeSlice() {
		// TODO Auto-generated method stub
		return null;
	}

    // @@protoc_insertion_point(class_scope:Timer)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Timer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Timer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025protoFile/Timer.proto\"\034\n\005Timer\022\023\n\013curr" +
      "entTime\030\001 \002(\003B\023\n\005protoB\nTimerProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Timer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Timer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Timer_descriptor,
              new java.lang.String[] { "CurrentTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
